name: CI

on:
  push:
    branches: [main]

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: dnf install -y curl dnf-utils rpm-build
      - run: curl -o a.rpm https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.109/1.fc39/src/chromium-120.0.6099.109-1.fc39.src.rpm
      - run: dnf builddep -y --srpm a.rpm
      - run: rpmbuild --rebuild a.rpm
