name: CI

on:
  push:
    branches: [main]

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: df
      - run: dnf install -y curl dnf-utils rpm-build
      - run: curl -o a.rpm https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.109/1.fc39/src/chromium-120.0.6099.109-1.fc39.src.rpm
      - run: ls -l a.rpm
      - run: dnf builddep -y --srpm a.rpm
      - run: df
      - run: rpm -ivh a.rpm
      - run: rm a.rpm
      - run: pushd ~/rpmbuild/SPECS/ && rpmbuild -bp chromium.spec && popd
      - run: find ~/rpmbuild/BUILD -type d -name 'third_*' -exec ls -l {} \;
      - run: df
