name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
    tags:
      - RUN*

jobs:
  fetch-source:
    runs-on: ubuntu-24.04
    container: fedora:40
    permissions:
      contents: write
    steps:
      - run: cat /etc/os-release
      - run: df
      - run: dnf install -y curl dnf-utils rpm-build git
      - uses: actions/checkout@v4
      - run: git clone -b 129.0.6658.0 --depth 1 --recurse-submodules=third_party/skia --recurse-submodules=third_party/ots/src/  --shallow-submodules https://chromium.googlesource.com/chromium/src chromium
      - run: pushd chromium && tar -czpf ${GITHUB_WORKSPACE}/before.tgz skia third_party/ots third_party/skia third_party/blink/renderer/platform chrome/VERSION && popd
#      - run:  ./chromium-latest.py --version 129.0.6658.0 --ffmpegclean --ffmpegarm
      - run: df
      - uses: actions/upload-artifact@v4
        with:
          name: before-main
          path: before.tgz

  cache-clean:
    runs-on: ubuntu-24.04
    container: fedora:40
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-chromium-clean
        with:
          path: |
            chromium-129.0.6658.0-clean.tar.xz
          key: chromium-129.0.6658.0
          enableCrossOsArchive: true
      - run: pwd
      - run: ls -Rl .
      - run: dnf install -y xz
      - run: pwd
      - run: ls -lR .
      - name: Build cache
        if: ${{ steps.cache-chromium-clean.outputs.cache-hit != 'true' }}
        run: ./chromium-latest.py --version 129.0.6658.0 --ffmpegclean --ffmpegarm

  fedora-job:
    runs-on: ubuntu-24.04
    container: fedora:40
    needs: cache-clean
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-chromium-clean
        with:
          path: |
            chromium-129.0.6658.0-clean.tar.xz
          key: chromium-129.0.6658.0
          enableCrossOsArchive: true
      - run: ls -Rl .
      - run: ls -lR chromium-129.0.6658.0*
      - run: cat /etc/os-release
      - run: df
      - run: dnf install -y curl dnf-utils rpm-build
      - run: curl -o a.rpm https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.216/1.fc39/src/chromium-120.0.6099.216-1.fc39.src.rpm
      - run: ls -l a.rpm
      - run: dnf builddep -y --srpm a.rpm
      - run: df
      - run: rpm -ivh a.rpm
      - run: rm a.rpm
      - run: rm -f ~/rpmbuild/SOURCES/chromium-*-clean.tar.xz
      - run: cp -p chromium-129.0.6658.0-clean.tar.xz ~/rpmbuild/SOURCES/
      - run: patch ~/rpmbuild/SPECS/chromium.spec chromium.spec.diff
      - run: cp 000*.patch ~/rpmbuild/SOURCES/
      - run: cp github.com/chromium/chromium/commit/*.patch ~/rpmbuild/SOURCES/
#      - run: pushd ~/rpmbuild/SPECS/ && rpmbuild -bp chromium.spec && popd
#      - run: find ~/rpmbuild/BUILD -type d -name 'third_*' -print -exec ls -l {} \;
#      - run: find ~/rpmbuild/BUILD -depth -type d -name 'third_*' -exec du {} \;
#      - run: du -s ~/rpmbuild/BUILD/chromium-*/third_party/*
#      - run: du -s ~/rpmbuild/BUILD/chromium-*/third_party/*/third_party
#      - run: du -s ~/rpmbuild/BUILD/chromium-*
#      - run: df
      - run: pushd ~/rpmbuild/SPECS/ && rpmbuild -bc chromium.spec && popd
      - run: mkdir after after-big
      - run: find ~/rpmbuild/BUILD/chromium-* -type f -name libskia.a -print -exec llvm-nm -C {} \;
      - run: find ~/rpmbuild/BUILD/chromium-* -type f -name libots.a -print -exec llvm-nm -C {} \;
      - run: find ~/rpmbuild/BUILD/chromium-* -type f -name libblink_platform.a -print -exec llvm-nm -C {} \;
      - run: tar -cJpf after.txz ~/rpmbuild/BUILD/chromium-*/out/Release/
      - uses: actions/upload-artifact@v4
        with:
          name: before
          path: before.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: after
          path: after.txz
      - run: df
